# Generated by Django 4.2.2 on 2023-08-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profiles_city_profiles_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Photo',
            field=models.ImageField(null=True, upload_to='Profile/'),
        ),
    ]
