# Generated by Django 4.2.2 on 2023-08-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Company', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('EmailAddress', models.EmailField(max_length=254, unique=True)),
                ('Location', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Jobtype', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Termporary', 'Termporary')], max_length=255)),
                ('Vacancy', models.PositiveIntegerField()),
                ('Experiencse', models.PositiveIntegerField()),
                ('Web', models.URLField()),
                ('slug', models.SlugField()),
                ('Pulished_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobsApp.categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('CV', models.FileField(upload_to='')),
                ('CoverLetter', models.TextField()),
                ('Jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobsApp.job')),
            ],
        ),
    ]
