# Generated by Django 4.2.2 on 2023-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0002_alter_job_experiencse_alter_job_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
