# Generated by Django 4.2.2 on 2023-08-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0004_remove_job_address_remove_job_phone_remove_job_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
