# Generated by Django 4.2.2 on 2023-08-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0005_applyjob_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner',
            new_name='Owner',
        ),
    ]
